language: php
php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly
before_script:
  - composer self-update
  - composer install --dev

script: 
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

notifications:
  email:
    - ricardojesus.ruizcruz@gmail.com