version: '2'
    services:
        web:
            image: apachephp:5.6
            ports:
                - "80:80"
                - "445:443"
                - "8116:22"
            volumes:
                - ./:/var/www/html
                - ~/.ssh:/home/magento2/.ssh
                - ../apache_vhost:/etc/apache2/sites-available/
            environment:
                - WEBSERVER_USER=www-data
                - MAGENTO_USER=magento2
                - CURRENT_USER_UID=501
                - MAGENTO_GROUP=501
                - REMOTE_HOST_DEBUG=192.168.1.64
                - XDEBUG_CONFIG=remote_host=192.168.1.64
                - PHP_IDE_CONFIG=serverName=localhost
            links:
                - mysql
            container_name: rioxygen-wrapper-web
        mysql:
            image: mysql:5.7
            ports:
              - 3307:33006
            environment:
                - MYSQL_ROOT_PASSWORD=mysql
                - MYSQL_DATABASE=zf2auth
            container_name: rioxygen-wrapper-db
        elasticsearch-master:
          image: danielguerra/alpine-elasticsearch
          restart: always
          command: -Des.network.bind_host=elasticsearch-master --cluster.name=graylog --node.name=elasticsearch-master --discovery.zen.ping.multicast.enabled=false --network.host=elasticsearch-master
          hostname: elasticsearch-master
          volumes:
           - elastic-data:/usr/share/elasticsearch/data
          ports:
           - "9200:9200"
           - "9300:9300"

         elasticsearch-node01:
          image: danielguerra/alpine-elasticsearch
          restart: always
          command: -Des.network.bind_host=elasticsearch-node01 --cluster.name=graylog --node.name=elasticsearch-node01 --discovery.zen.ping.unicast.hosts=master:9300  --network.host=elasticsearch-node01
          hostname: elasticsearch-node01
          links:
           - "elasticsearch-master:master"
          volumes:
            - elastic-data:/usr/share/elasticsearch/data

         mongodb:
          image: mongo:3
          restart: always
          command: "mongod --smallfiles"
          ports:
           - "27017:27017"
          volumes:
           - mongodb-conf:/etc/mongod.conf:ro
           - mongodb-data:/data/db

         graylog:
          image: "graylog2/server"
          restart: always
          volumes:
           - graylog-data:/usr/share/graylog/data/journal
           - graylog-conf:/usr/share/graylog/data/config
          environment:
              GRAYLOG_PASSWORD_SECRET: somepasswordpepper
              GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
              GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
          ports:
           - "9000:9000"
           - "12201:12201"
           - "12201:12201/udp"
          links:
           - mongodb:mongo
           - elasticsearch-master:elasticsearch
          depends_on:
           - mongodb
           - elasticsearch-master
           - elasticsearch-node01

        volumes:
         mongodb-data:
         mongodb-conf:
         graylog-data:
         graylog-conf:
         elastic-data: